In [1]:
import numpy as np

In [2]:
board = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]  
]
board = np.array(board)

In [36]:
def print_board():
    
    square_len = len(board[0]) // 3 * 5
    tab_len = (len(board) - 1) // 3 * 3
    
    print("{}{}".format(
            '-' * square_len, 
            '-' * tab_len
        )
    )
    for i in range(len(board)):
        if i > 0 and i % 3 == 0: print()
        for j in range(len(board[i])):
            if j > 0 and j % 3 == 0: print("\t", end="")
            print("{} ".format(board[i,j]), end="")
        print()
    print("{}{}".format(
            '-' * square_len, 
            '-' * tab_len
        )
    )

In [37]:
print_board()

---------------------
5 3 0 	0 7 0 	0 0 0 
6 0 0 	1 9 5 	0 0 0 
0 9 8 	0 0 0 	0 6 0 

8 0 0 	0 6 0 	0 0 3 
4 0 0 	8 0 3 	0 0 1 
7 0 0 	0 2 0 	0 0 6 

0 6 0 	0 0 0 	2 8 0 
0 0 0 	4 1 9 	0 0 5 
0 0 0 	0 8 0 	0 7 9 


In [6]:
def possible(x: int, y: int, n: int)->bool:
    global board
    
    sq_x = 3 * (x // 3)
    sq_y = 3 * (y // 3)
    
    # if in square return false
    if n in board[sq_y:sq_y + 3, sq_x:sq_x + 3]: return False
    
    # if in row return false
    if n in board[y]: return False
    
    # if in column return false
    if n in np.transpose(board)[x]: return False
    
    return True
    

In [7]:
def solve():
    global board
    
    for x in range(len(board[0])):
        for y in range(len(board)):
            if board[y,x] == 0:
                for n in range(1, 10):
                    if possible(x, y, n):
                        board[y,x] = n
                        solve()
                        board[y,x] = 0
                return
    print(board)
                
            

In [8]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
